project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from wavepool import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.front_page, name='home'),
    path('instructions', views.instructions, name='instructions'),
    path('news/', views.article, name='article')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wavepool/models.py
from django.db import models
import datetime


class NewsPost(models.Model):
    title = models.CharField(max_length=300)
    body = models.TextField(max_length=3000)
    source = models.URLField()
    is_cover_story = models.BooleanField(default=False)
    publish_date = models.DateField(default=datetime.date.today())

    @property
    def teaser(self):
        return self.body[:150]


class UserStory(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField(max_length=1000)

    def __str__(self):
        return self.title


class AcceptanceCriteria(models.Model):
    UserStory = models.ForeignKey(UserStory, on_delete=models.CASCADE)
    ac = models.TextField(max_length=3000)

wavepool/views.py
from django.template import loader
from django.http import HttpResponse

from wavepool.models import NewsPost, UserStory


def front_page(request):
    template = loader.get_template('wavepool/frontpage.html')
    cover_story = NewsPost.objects.get(is_cover_story=True)
    newsposts = NewsPost.objects.all()
    context = {
        'cover_story': cover_story,
        'top_stories': newsposts[0:3],
        'archive': newsposts,
    }

    return HttpResponse(template.render(context, request))


def article(request):
    template = loader.get_template('wavepool/article.html')
    article = NewsPost.objects.get(pk=1)
    context = {
        'article': article
    }

    return HttpResponse(template.render(context, request))


def instructions(request):
    template = loader.get_template('wavepool/instructions.html')
    user_stories = UserStory.objects.all()
    context = {
        'user_stories': user_stories
    }
    return HttpResponse(template.render(context, request))

wavepool/templates/wavepool/article.html
{% extends 'wavepool/base.html' %}
{% load static %}

{% block page_content %}
	<div class="row"><a href=""><button>edit</button></a></div>
	<div class="row">
		<h1>{{ article.title }}</h1>
	</div>
	<div class="row">
		{{ article.body}}
	</div>
{% endblock %}

wavepool/templates/wavepool/base.html
{% load static %}
<html>
	<head>
  		<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  		<link href="{% static 'app.css' %}" rel="stylesheet">
	</head>
	<body>
		<div class="container-fluid">
			<nav class="navbar navbar-expand-lg navbar-light bg-light">
			  <a class="navbar-brand" href="{% url 'home' %}">Wavepool</a>
			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
			  </button>

			  <div class="collapse navbar-collapse" id="navbarSupportedContent">
			    <ul class="navbar-nav mr-auto">
			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'instructions' %}">Instructions</a>
			      </li>
			    </ul>
			  </div>
			</nav>
		</div>
		<div id="page_content" class="container">
			{% block page_content %}{% endblock %}
		</div>
	</body>
</html>

wavepool/templates/wavepool/frontpage.html
{% extends 'wavepool/base.html' %}
{% load static %}

{% block page_content %}
	<div class="row">
		<div class="col-md-4">
			<div id="coverstory" class="row" data-story-id="{{cover_story.pk}}">
				<h2>Cover story</h2>
				<div><a href="{% url 'article' %}">{{ cover_story.title }}</a></div>
				<div><img src="media/image/placeholder-img.jpg"  width="300" height="175" /></div>
				<div class="article-teaser" data-story_id="{{cover_story.pk}}">{{ cover_story.teaser }} ...</div>
			</div>
		</div>
		<div id="topstories" class="col-md-8">
			<div class="row"><h2>Top Stories</h2></div>
			<div class="row">
				{% for newspost in top_stories %}
				<div class="topstory" data-story-id="{{newspost.pk}}" data-top-story-placement="{{forloop.counter}}"><a href="{% url 'article' %}">{{ newspost.title }}</a></div>
				<div class="article-teaser" data-story_id="{{newspost.pk}}">{{ newspost.teaser }} ...
					<hr />
				</div>

				{% endfor %}
			</div>
		</div>
	</div>
	<div id="frontpage-archive">
		<div class="row"><h2>Archive</h2></div>
		<div class="row">
			<div id="archive-stories">
				{% for newspost in archive %}
					<div class="archived-story" data-archive-story-id="{{newspost.pk}}">
						<div class="frontpage-archive_link"><a href="{% url 'article' %}">{{ newspost.title }}</a></div>
						<div class="article-teaser" data-story_id="{{newspost.pk}}">{{ newspost.teaser }} ...</div>
					</div>
					<hr />
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}

wavepool/templates/wavepool/instructions.html
{% extends 'wavepool/base.html' %}

{% block page_content %}
	<div id="instructions">
		<div class="container">
			<div class="row">
				<h1>Code Exercise Instructions</h1>
				<p>For each ticket below, submit a pull request to this repository that completes the request, meeting as many of the acceptance criteria as you can. For each acceptance criteria, a django test is noted which should pass if your solution is valid.<p>

				</p>For each pull request, include instructions for the reviewer to verify the behavior as well as commentary about your solutions.</p>
			</div>
		</div>
			{% for user_story in user_stories %}
			<div class="card">
  				<div class="card-header"><h1 class="card-title">{{user_story.title}}</h1></div>
  				<div class="card-body">
	  				<p class="card-text">{{user_story.description}}</p>
	  				<h2 class="card-title">Acceptance Criteria:</h2>
						<ul>
						{% for ac in user_story.acceptancecriteria_set.all %}
							<li class="instructable-ac">{{ac.ac|safe}}</li>
						{% endfor %}
						</ul>
					</li>
	  			</div>
  			</div>
			{% endfor %}
	</div>
{% endblock %}